INSERT INTO TBL_STICKER (NAME, TEAM, TYPE, NUMBER, DOUBLES) VALUES ('Antony', 'Brazil', 'Comum', 'BRA 15', 0);
INSERT INTO TBL_STICKER (NAME, TEAM, TYPE, NUMBER, DOUBLES) VALUES ('Gabriel Jesus', 'Brazil', 'Comum', 'BRA 16', 2);
INSERT INTO TBL_STICKER (NAME, TEAM, TYPE, NUMBER, DOUBLES) VALUES ('Viníciius Júnior', 'Brazil', 'Comum', 'BRA 20', 0);